### ISSUE TITLE
Mejor delegar y reutilizar

### ISSUE THREAD

**Issue by matifreyre** [iguardines/microprocesador#2]
La definición está perfecta, pero como tenés que hacer exactamente lo mismo en otras instrucciones podrías definirle un nombre genérico y que este sea un sinónimo de esa y que las demás compongan esa auxiliar con la tarea propia de la instrucción, para no tener que acceder al PC con cada una de las instrucciones. No te digo usar directamente esta porque así las podés separar (con vistas a la entrega 2).

https://github.com/iguardines/microprocesador/blob/feecae0941f8cb5b0998b3d232342773ef66b4bb/microprocesador.hs#L11-L13

**Comment by iguardines** [comment]
Fix #2 03182e8015c3f0f635f060badf09894046a191f7 se sube el cambio para reutilizar y dejar mas generico el incpc
