### ISSUE TITLE
div es una función que ya existe

### ISSUE THREAD

**Issue by matifreyre** [iguardines/microprocesador#3]
Fijate que en el punto 5.1 sugiere nombres de funciones para todos los puntos a desarrollar. Te recomiendo usarlos para evitar este tipo de problemas.

https://github.com/iguardines/microprocesador/blob/feecae0941f8cb5b0998b3d232342773ef66b4bb/microprocesador.hs#L21-L24

**Comment by matifreyre** [comment]
De hecho, siendo los acumuladores números enteros, la división que querés hacer es entera, ahí usás `div`, pero no puede ser el nombre de tu función.
Además, fijate que podés necesitar cambiar el mensaje de error.

**Comment by iguardines** [comment]
Cambiado a: "divide micro".
